tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "awscli"
brew "composer"
brew "nvm"
brew "curl"
brew "git"
brew "trash"
brew "homebrew/cask-fonts/font-fira-code"
brew "homebrew/cask-fonts/font-jetbrains-mono"
brew "tree"
brew "speedtest-cli"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "sqlite"
brew "mkcert"
brew "bandwhich"

# Apps
brew "iterm2"
brew "dropbox"
brew "slack"
brew "discord"
brew "firefox"
brew "google-chrome"
brew "opera"
brew "aware"
brew "docker"
brew "vlc"
brew "sublime-text"
brew "whatsapp"
brew "forklift"
brew "numi"
brew "ticktick"
brew "skype"
brew "github"
brew "tableplus"
brew "timemachineeditor"

cask 'the-unarchiver'
cask 'visual-studio-code'

# bandwidth+, photoscapex, cointick, sip, craft, twitch studio
